site_name: 2nd
theme: 
  name: material
  highlightjs: true
  font:
    text:  inter

nav:
  - Home: 
    - Français:
        - Séquence 1: 
          - Séance 1: 'Français/Sequence 1/Seance 1.md'
          - Séance 2: 'Français/Sequence 1/Seance 2.md'
        - Figures de styles - Complet : 'Français/FdS_F.md'
        - Figures de styles - A Apprendre : 'Français/FdS_nF.md'
    - Maths : 
      - Ensembles de nombres 1/3 : 'Maths/Ensembles de nombres.md'
      - Algorithmique et programmation 1/2 : 'Maths/Algorithmique et programmation.md'
    - Histoire : 
      - La méditerrannée Antique : 'Histoire/CH1.md'
      - La méditerrannée Antique Révisions : 'Histoire/CH1_R.md'
    # - Histoire :
    # - Anglais : 
    # - Italien : 
    # - Maths : 
    # - PC : 
    # - SNT :
    # - SVT : 
  - 'about.md'
  - 'Issue Tracker': 'https://example.com/'





extra_css:
  - extra.css
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/css/massilia-mermaid.css

extra_javascript:
  - mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.13.8/mermaid.min.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/massilia-mermaid.js

markdown_extensions:
  - smarty
  - sane_lists
  - admonition
  - legacy_attrs
  - pymdownx.caret
  - pymdownx.extra
  - pymdownx.blocks.details
  - pymdownx.blocks.caption
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format